version: '3'
services:
  freespeech-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: freespeech/api
    ports:
      - '${APP_PORT:-3000}:3000'
    depends_on:
      - mongo
    volumes:
      - '.:/APP'
      - '/APP/node_modules'
    networks:
      - freespeech
  mongo:
    image: mongo
    restart: always
    ports:
      - "27019:27019"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - 'freespeech-db:/data/db'
    networks:
      - freespeech
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/
    networks:
      - freespeech
networks:
  freespeech:
    driver: bridge
volumes:
  freespeech-db:
    driver: local
